### ISSUE TITLE
query

### ISSUE THREAD

**Issue by YALLAULLATEJASWI** [vikneswaran20/CarPool#1]
can i know how did u connect the microsoft visual studio with oracle?

**Comment by vikneswaran20** [comment]
Using **System.Data.OracleClient** module

**Comment by YALLAULLATEJASWI** [comment]
CAN U JUST SHOW ME CONNECTING IT IN MY TEAM VIEWER IN MY LAPTOP ANS SHOW PLEASE

**Comment by YALLAULLATEJASWI** [comment]
CAN I HAVE UR CONTACT FOR DOING THIS
